# Generated by Django 4.0.6 on 2023-07-11 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='organization',
            new_name='group',
        ),
    ]
