# Generated by Django 4.0.6 on 2023-07-11 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_count',
        ),
    ]
