# Generated by Django 4.0.6 on 2023-07-13 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_remove_product_product_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomsModel',
        ),
    ]
