# Generated by Django 4.0.6 on 2023-07-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_actionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionhistory',
            name='changed_model_name',
            field=models.CharField(default='salom', max_length=50),
            preserve_default=False,
        ),
    ]
