# Generated by Django 4.0.6 on 2023-07-18 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0007_actionhistory_data_alter_actionhistory_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionhistory',
            name='inventar_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='inventar_number'),
        ),
        migrations.AlterField(
            model_name='actionhistory',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='actionhistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
